version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  flask-app:
    build:
      context: .
      dockerfile: ./dockerflask/Dockerfile
    container_name: flask-app
    ports:
      - "5000:5000"
    depends_on:
      - kafka
      - redis
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  celery-worker:
    build:
      context: .
      dockerfile: ./dockercelery/Dockerfile
    container_name: celery-worker
    depends_on:
      - kafka
      - redis
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      REDIS_URL: "redis://redis:6379/0"

